"""Add nft_generation_jobs table

Revision ID: 0727a5ddb7d0
Revises: 33e73071ca55
Create Date: 2026-09-13 17:29:55.963175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0727a5ddb7d0'
down_revision = '33e73071ca55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('items_generated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['nft_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nft_generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_generation_jobs_collection_id'), ['collection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nft_generation_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_generation_jobs_collection_id'))

    op.drop_table('nft_generation_jobs')
    # ### end Alembic commands ###
