"""wallet identities: accounts span wallets

Revision ID: 0dc6f4b54f7f
Revises: b7283ef4adcf
Create Date: 2026-09-24 12:45:12.454732

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc6f4b54f7f'
down_revision = 'b7283ef4adcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', 'chain', name='uq_wallet_identities_wallet_chain')
    )
    with op.batch_alter_table('wallet_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_identities_user_id'), ['user_id'], unique=False)

    # Backfill: every existing account's own wallet becomes its first linked
    # wallet — without this, sign-in (which now resolves accounts through
    # wallet_identities) would create a fresh, empty account for every
    # existing user.
    bind = op.get_bind()
    users = bind.execute(sa.text("SELECT id, wallet_address, chain, created_at FROM users")).fetchall()
    for user_id, wallet_address, chain, created_at in users:
        bind.execute(
            sa.text(
                "INSERT INTO wallet_identities (id, user_id, wallet_address, chain, created_at) "
                "VALUES (:id, :user_id, :wallet_address, :chain, :created_at)"
            ),
            {"id": str(uuid.uuid4()), "user_id": user_id, "wallet_address": wallet_address, "chain": chain, "created_at": created_at},
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_wallet_chain'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # Drops every linked wallet: after a downgrade each account signs in
    # only with the wallet that created it again. Re-adding the unique
    # constraint fails if a wallet was unlinked and then started its own
    # account (two users rows with the same wallet) — resolve those by hand.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_wallet_chain'), ['wallet_address', 'chain'])

    with op.batch_alter_table('wallet_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_identities_user_id'))

    op.drop_table('wallet_identities')
    # ### end Alembic commands ###
