"""solana pool actions

Revision ID: 22c85dec71ba
Revises: 967a078cb6e6
Create Date: 2026-09-25 06:28:17.836793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c85dec71ba'
down_revision = '967a078cb6e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solana_pool_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('launch_id', sa.String(length=36), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('pool_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('token_amount', sa.String(length=32), nullable=False),
    sa.Column('sol_amount', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['launch_id'], ['solana_token_launches.id'], name='fk_solana_pool_actions_launch_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_solana_pool_actions_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solana_pool_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solana_pool_actions_launch_id'), ['launch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solana_pool_actions_signature'), ['signature'], unique=True)
        batch_op.create_index(batch_op.f('ix_solana_pool_actions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solana_pool_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solana_pool_actions_user_id'))
        batch_op.drop_index(batch_op.f('ix_solana_pool_actions_signature'))
        batch_op.drop_index(batch_op.f('ix_solana_pool_actions_launch_id'))

    op.drop_table('solana_pool_actions')
    # ### end Alembic commands ###
