"""candy machine mint limit

Revision ID: 322bde6470fd
Revises: cec1aa1d4efc
Create Date: 2026-09-24 07:01:57.508662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322bde6470fd'
down_revision = 'cec1aa1d4efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mint_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.drop_column('mint_limit')

    # ### end Alembic commands ###
