"""Unique constraint on contract_deployments.transaction_hash

Revision ID: 33e73071ca55
Revises: c321d1a006b0
Create Date: 2026-09-05 15:44:56.379063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e73071ca55'
down_revision = 'c321d1a006b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_deployments_transaction_hash'), ['transaction_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_deployments_transaction_hash'))

    # ### end Alembic commands ###
