"""candy machine allowlist phase

Revision ID: 5ada70d9c110
Revises: ecdc3b02bcb4
Create Date: 2026-09-24 01:45:04.780453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ada70d9c110'
down_revision = 'ecdc3b02bcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowlist', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.drop_column('allowlist')

    # ### end Alembic commands ###
