"""solana token metadata locked

Revision ID: 643f5fd03804
Revises: 0dc6f4b54f7f
Create Date: 2026-09-24 17:23:24.551355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643f5fd03804'
down_revision = '0dc6f4b54f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solana_token_launches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_locked', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solana_token_launches', schema=None) as batch_op:
        batch_op.drop_column('metadata_locked')

    # ### end Alembic commands ###
