"""link contract deployments to nft collections

Revision ID: 6eb22073357c
Revises: a126c4b6bc87
Create Date: 2026-09-24 01:14:11.769084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eb22073357c'
down_revision = 'a126c4b6bc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nft_collection_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_contract_deployments_nft_collection_id'), ['nft_collection_id'], unique=False)
        # Named explicitly (autogenerate left it None) so downgrade can drop it.
        batch_op.create_foreign_key('fk_contract_deployments_nft_collection_id', 'nft_collections', ['nft_collection_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contract_deployments_nft_collection_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contract_deployments_nft_collection_id'))
        batch_op.drop_column('nft_collection_id')

    # ### end Alembic commands ###
