"""liquidity provisions

Revision ID: 967a078cb6e6
Revises: e7a95ea60838
Create Date: 2026-09-25 02:40:19.582979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967a078cb6e6'
down_revision = 'e7a95ea60838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquidity_provisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('dex_name', sa.String(length=64), nullable=False),
    sa.Column('pair_address', sa.String(length=64), nullable=False),
    sa.Column('provider_address', sa.String(length=64), nullable=False),
    sa.Column('transaction_hash', sa.String(length=128), nullable=False),
    sa.Column('token_amount', sa.String(length=80), nullable=False),
    sa.Column('native_amount', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['contract_deployments.id'], name='fk_liquidity_provisions_deployment_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_liquidity_provisions_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liquidity_provisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liquidity_provisions_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_liquidity_provisions_transaction_hash'), ['transaction_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_liquidity_provisions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liquidity_provisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liquidity_provisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_liquidity_provisions_transaction_hash'))
        batch_op.drop_index(batch_op.f('ix_liquidity_provisions_deployment_id'))

    op.drop_table('liquidity_provisions')
    # ### end Alembic commands ###
