"""add solana_token_launches table

Revision ID: a126c4b6bc87
Revises: 0727a5ddb7d0
Create Date: 2026-09-24 00:57:09.123917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a126c4b6bc87'
down_revision = '0727a5ddb7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solana_token_launches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('mint_address', sa.String(length=64), nullable=False),
    sa.Column('transaction_signature', sa.String(length=128), nullable=False),
    sa.Column('creator_wallet', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('supply_raw', sa.String(length=32), nullable=False),
    sa.Column('metadata_uri', sa.String(length=256), nullable=True),
    sa.Column('mint_authority_revoked', sa.Boolean(), nullable=False),
    sa.Column('freeze_authority_revoked', sa.Boolean(), nullable=False),
    sa.Column('explorer_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_signature')
    )
    with op.batch_alter_table('solana_token_launches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solana_token_launches_mint_address'), ['mint_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_solana_token_launches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solana_token_launches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solana_token_launches_user_id'))
        batch_op.drop_index(batch_op.f('ix_solana_token_launches_mint_address'))

    op.drop_table('solana_token_launches')
    # ### end Alembic commands ###
