"""solana pool action lp amount

Revision ID: a4bbdf1eea63
Revises: 22c85dec71ba
Create Date: 2026-09-25 08:34:18.242689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4bbdf1eea63'
down_revision = '22c85dec71ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solana_pool_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lp_amount', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solana_pool_actions', schema=None) as batch_op:
        batch_op.drop_column('lp_amount')

    # ### end Alembic commands ###
