"""initial schema

Revision ID: b6810d19e11d
Revises: 
Create Date: 2026-08-19 09:14:26.344789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6810d19e11d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', 'chain', name='uq_users_wallet_chain')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_wallet_address'), ['wallet_address'], unique=False)

    op.create_table('wallet_nonces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_nonces_wallet_address'), ['wallet_address'], unique=False)

    op.create_table('contract_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('contract_address', sa.String(length=128), nullable=False),
    sa.Column('transaction_hash', sa.String(length=128), nullable=False),
    sa.Column('deployer_address', sa.String(length=128), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('deployment_cost_native', sa.Float(), nullable=True),
    sa.Column('explorer_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_deployments_contract_address'), ['contract_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_deployments_user_id'), ['user_id'], unique=False)

    op.create_table('nft_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('collection_size', sa.Integer(), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nft_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_collections_user_id'), ['user_id'], unique=False)

    op.create_table('candy_machine_deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nft_collection_id', sa.String(length=36), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('collection_mint', sa.String(length=64), nullable=False),
    sa.Column('candy_machine', sa.String(length=64), nullable=False),
    sa.Column('price_sol', sa.Float(), nullable=False),
    sa.Column('items_available', sa.Integer(), nullable=False),
    sa.Column('go_live_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_wallet', sa.String(length=64), nullable=False),
    sa.Column('transaction_signatures', sa.JSON(), nullable=False),
    sa.Column('explorer_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nft_collection_id'], ['nft_collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candy_machine_deployments_candy_machine'), ['candy_machine'], unique=False)
        batch_op.create_index(batch_op.f('ix_candy_machine_deployments_collection_mint'), ['collection_mint'], unique=False)
        batch_op.create_index(batch_op.f('ix_candy_machine_deployments_nft_collection_id'), ['nft_collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candy_machine_deployments_user_id'), ['user_id'], unique=False)

    op.create_table('nft_generated_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('token_index', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.Column('ipfs_image_hash', sa.String(length=128), nullable=True),
    sa.Column('ipfs_metadata_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['nft_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nft_generated_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_generated_items_collection_id'), ['collection_id'], unique=False)

    op.create_table('nft_layers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['nft_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nft_layers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_layers_collection_id'), ['collection_id'], unique=False)

    op.create_table('nft_traits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('layer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rarity_weight', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['nft_layers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nft_traits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_traits_layer_id'), ['layer_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('project_type', sa.String(length=32), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('draft_data', sa.JSON(), nullable=False),
    sa.Column('contract_deployment_id', sa.String(length=36), nullable=True),
    sa.Column('nft_collection_id', sa.String(length=36), nullable=True),
    sa.Column('candy_machine_deployment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candy_machine_deployment_id'], ['candy_machine_deployments.id'], ),
    sa.ForeignKeyConstraint(['contract_deployment_id'], ['contract_deployments.id'], ),
    sa.ForeignKeyConstraint(['nft_collection_id'], ['nft_collections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('nft_traits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_traits_layer_id'))

    op.drop_table('nft_traits')
    with op.batch_alter_table('nft_layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_layers_collection_id'))

    op.drop_table('nft_layers')
    with op.batch_alter_table('nft_generated_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_generated_items_collection_id'))

    op.drop_table('nft_generated_items')
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candy_machine_deployments_user_id'))
        batch_op.drop_index(batch_op.f('ix_candy_machine_deployments_nft_collection_id'))
        batch_op.drop_index(batch_op.f('ix_candy_machine_deployments_collection_mint'))
        batch_op.drop_index(batch_op.f('ix_candy_machine_deployments_candy_machine'))

    op.drop_table('candy_machine_deployments')
    with op.batch_alter_table('nft_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_collections_user_id'))

    op.drop_table('nft_collections')
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_deployments_user_id'))
        batch_op.drop_index(batch_op.f('ix_contract_deployments_contract_address'))

    op.drop_table('contract_deployments')
    with op.batch_alter_table('wallet_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_nonces_wallet_address'))

    op.drop_table('wallet_nonces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wallet_address'))

    op.drop_table('users')
    # ### end Alembic commands ###
