"""link projects to solana token launches

Revision ID: b7283ef4adcf
Revises: 322bde6470fd
Create Date: 2026-09-24 07:29:51.107979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7283ef4adcf'
down_revision = '322bde6470fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solana_token_launch_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_projects_solana_token_launch_id', 'solana_token_launches', ['solana_token_launch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_solana_token_launch_id', type_='foreignkey')
        batch_op.drop_column('solana_token_launch_id')

    # ### end Alembic commands ###
