"""Unique constraint on candy_machine_deployments.candy_machine

Revision ID: c321d1a006b0
Revises: b6810d19e11d
Create Date: 2026-08-19 22:45:39.146463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c321d1a006b0'
down_revision = 'b6810d19e11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candy_machine_deployments_candy_machine'))
        batch_op.create_index(batch_op.f('ix_candy_machine_deployments_candy_machine'), ['candy_machine'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candy_machine_deployments_candy_machine'))
        batch_op.create_index(batch_op.f('ix_candy_machine_deployments_candy_machine'), ['candy_machine'], unique=False)

    # ### end Alembic commands ###
