"""candy machine prices seen

Revision ID: cec1aa1d4efc
Revises: 5ada70d9c110
Create Date: 2026-09-24 04:08:58.018230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec1aa1d4efc'
down_revision = '5ada70d9c110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prices_seen', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candy_machine_deployments', schema=None) as batch_op:
        batch_op.drop_column('prices_seen')

    # ### end Alembic commands ###
