"""nft trait rules

Revision ID: e7a95ea60838
Revises: 643f5fd03804
Create Date: 2026-09-24 17:59:27.725351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a95ea60838'
down_revision = '643f5fd03804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nft_trait_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('trait_id', sa.String(length=36), nullable=False),
    sa.Column('other_trait_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['nft_collections.id'], ),
    sa.ForeignKeyConstraint(['other_trait_id'], ['nft_traits.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['nft_traits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nft_trait_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nft_trait_rules_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_trait_rules_other_trait_id'), ['other_trait_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_nft_trait_rules_trait_id'), ['trait_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nft_trait_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nft_trait_rules_trait_id'))
        batch_op.drop_index(batch_op.f('ix_nft_trait_rules_other_trait_id'))
        batch_op.drop_index(batch_op.f('ix_nft_trait_rules_collection_id'))

    op.drop_table('nft_trait_rules')
    # ### end Alembic commands ###
