"""contract deployment source verification status

Revision ID: ecdc3b02bcb4
Revises: 6eb22073357c
Create Date: 2026-09-24 01:26:11.957400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdc3b02bcb4'
down_revision = '6eb22073357c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=16), server_default='unverified', nullable=False))
        batch_op.add_column(sa.Column('verification_guid', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('verification_message', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_deployments', schema=None) as batch_op:
        batch_op.drop_column('verification_message')
        batch_op.drop_column('verification_guid')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
